version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - net
    ports:
      - '3004:3004'

  redis:
    image: 'redis:alpine'
    networks:
      - net
    ports:
      - '6379:6379'

networks:
  net: